### ISSUE TITLE
is shows the skins i do not selected why?

### ISSUE THREAD

**Issue by Rafa223375** [Tamely/SaturnSwapper#104]
when i want to convert a skin it shows me anything but my skin. and i have a valid key...

![Screenshot 2023-12-22 101431](https://github.com/Tamely/SaturnSwapper/assets/154587344/ababbef3-1b81-45f5-acc4-cbd5b605b305)

**Comment by kazmerx** [comment]
same problem here

**Comment by ChrisGriffin2** [comment]
i asked on their disc and apparently cus u need transformative skins
