### ISSUE TITLE
false positive?

### ISSUE THREAD

**Issue by KamilosPolska** [Tamely/SaturnSwapper#108]
![image](https://github.com/Tamely/SaturnSwapper/assets/163676548/c3787539-f3af-4a28-bca0-9fef847407d4)
is it a false positive?

**Comment by Tamely** [comment]
You are looking at the source. Please decide that for yourself before asking any more stupid questions.

**Comment by l1nxxwrld** [comment]
first of all, why didn't you upload the exe of saturn? You can view the code of saturn, and also the false positive may have been caused by a multitude of different things, most likely the functionality of saturn.
