### ISSUE TITLE
"Key is already in use on another PC"

### ISSUE THREAD

**Issue by Storm99999** [Tamely/SaturnSwapper#109]
![image](https://github.com/Tamely/SaturnSwapper/assets/87811650/47fe15e9-5cf6-409a-85fb-750639c7a2c6)

**Comment by DaRixYTR** [comment]
me too bro, how a i can fix?

**Comment by Tamely** [comment]
This is closed as completed for a reason. If you'd read the discord server, you'd know V2 no longer works and is no longer being worked on. Use V3.

**Comment by VerzeHxD** [comment]
you gotta buy saturn+

**Comment by Ftonelli2329** [comment]
how i solve this error
![image](https://github.com/Tamely/SaturnSwapper/assets/172132359/40544bcf-cd49-4acb-b6e2-c20a0852c047)
