### ISSUE TITLE
Lobby Swapper 

### ISSUE THREAD

**Issue by snkdonkey** [Tamely/SaturnSwapper#71]
Is there anyway to lobby swap, like CID swap?

**Comment by Xtendera** [comment]
> 

... There is an option for it in the swapper.

**Comment by snkdonkey** [comment]
> 

every time i try that it doesn’t cid swap only swaps the skin.

**Comment by Tamely** [comment]
> > 
> 
> 
> 
> every time i try that it doesn’t cid swap only swaps the skin.

because you don't have Saturn+. Lobby swaps are only available to people that do.
