### ISSUE TITLE
Kicked

### ISSUE THREAD

**Issue by Ol3m** [Tamely/SaturnSwapper#83]
Everytime i play i get kicked and it says error in game installation or sum

**Comment by jayplash21** [comment]
Same thing happened for me., might be a recent update in fortnite that stops skin changers from changing skins.

**Comment by VerzeHxD** [comment]
> Same thing happened for me., might be a recent update in fortnite that stops skin changers from changing skins.

fortnite did a update and now ig swaps kick (only skins and backblings), where have u guys been for the past 2-3 updates?, they did this awhile ago

**Comment by luke1231-sys** [comment]
i get kickt every time i go in a game

**Comment by Tamely** [comment]
Crazy! Try reading!
